### ISSUE TITLE
start, end of article_pageviews

### ISSUE THREAD

**Issue by ThomasWilli** [Ironholds/pageviews#1]
hi. first of all, thanks for the package. I'm not sure if I'm doing things wrong, but I'm running into an error when specifying the start and end date of article_pageviews. 

For example when trying to download from a period starting first of January 2014 and ending first of April 2014: 

```
article_pageviews(project = "en.wikipedia", article = "R (programming language)", platform = "all",  user_type = "all", start = "2014010100", end = "2014040100", reformat = TRUE)

Error in pv_query(parameters, ...) : client error: (404) Not Found
```

It runs smoothly with different parameters (for example with `start = "2014100100", end = "2015100200"`). However, I don't understand why it works here, but not with other parameters. 

Thanks for you help.

**Comment by Ironholds** [comment]
Exactly what the response says; it doesn't have the data. I've asked the API maintainers to include a way of identifying what data it has, and to do something other than 404, but no dice yet :/.

**Comment by ThomasWilli** [comment]
alright. thx for the response.

**Comment by Ironholds** [comment]
One thing I can do is experiment with intercepting the messages and providing more meaningful R-side messages, at least. I'll re-open with that in mind.
