### ISSUE TITLE
`pageview_timestamps()` leads to Bad Request (HTTP 400) error

### ISSUE THREAD

**Issue by sheriferson** [Ironholds/pageviews#10]
Using `pageview_timestamps()` for the `start` or `end` parameters of `article_pageviews()` leads to a Bad Request (HTTP 400).

``` r
>>> ghviews <- article_pageviews(article = 'GitHub', 
                             end = pageview_timestamps(Sys.Date()))

Error in pv_query(parameters, ...) : Bad Request (HTTP 400).
```

If you replace `pageview_timestamps(Sys.Date()))` with `'2016090500'` it works fine. Seems like `pageview_timestamps()` returns `201609050100` which is two digits more than what works.

Am I missing something or doing something wrong, or is this a problem that needs fixing? (either due to a bug or a change in the API).

I know [you said](https://github.com/Ironholds/pageviews/issues/9#issuecomment-195819149) you weren't actively developing right now, but, if I fixed the function and sent a pull request, would it be accepted and pushed to the release version? No pressure, just asking to decide whether to put time/effort in to fix it.

**Comment by Ironholds** [comment]
Absolutely it would!

**Comment by sheriferson** [comment]
Actually, this issue is fixed in the dev version on Github:

Version: 0.2.9000

``` r
# cloned to local machine
> pageview_timestamps()
[1] "2016090500"
```

Compared to what you get from version 0.2.0 on CRAN:

``` r
# pageviews from CRAN
> pageviews::pageview_timestamps()
[1] "201609050100"
```

So I think all that's needed is to publish the GitHub version to CRAN.
