### ISSUE TITLE
Adding granularity="monthly" to article_pageviews

### ISSUE THREAD

**Issue by pssguy** [Ironholds/pageviews#13]
It looks from your code as though the data can be accessed in this manner but you do not offer it as option in package? Presumably if I was after a few months data for an article it would be quicker than getting all days and then processing

**Comment by Ironholds** [comment]
Unfortunately the package is structured as it is to provide for a consistent internal API and make it possible to include monthly-granularity data when the pageviews API provides it - which it currently doesn't :(
