### ISSUE TITLE
Month = "all" / Day = "all" does not work for top articles function.

### ISSUE THREAD

**Issue by jeremiahpslewis** [Ironholds/pageviews#2]
Example: `top_articles(project = "en.wikipedia", year = "2015", month = "all", day = "all")`
Error: `The pageview data available does not cover the range you requested`

I've tested this in the Wikipedia API explorer and it appears to be an issue on their side.
Just wanted to flag this in case anyone runs into the same issue.

**Comment by Ironholds** [comment]
Well, yep. You can't ask for all of 2015 because it doesn't have all of 2015's data (we've only got from, iirc, August).

I'll update the docs to make the restrictions clearer, and maybe remove the month=all option entirely since it seems...extraneous until at least the end of 2016 ;p.

**Comment by jeremiahpslewis** [comment]
Gotcha. Thanks for a nice package!
