### ISSUE TITLE
special characters and URI encoding

### ISSUE THREAD

**Issue by ThomasWilli** [Ironholds/pageviews#3]
Hi 
I only found out that the error thrown at me has to do with encoding issues. After a quick search I found that the API requires URI-encoded articles. 

```
URI <- function(x){
      x <- gsub("ü", "%C3%BC", x)
      x <- gsub("Ü", "%C3%9C", x)
      x <- gsub("ä", "%C3%A4", x)
      x <- gsub("Ä", "%C3%84", x)
      x <- gsub("ö", "%C3%B6", x)
      x <- gsub("Ö", "%C3%96", x)
      x <- gsub("é", "%C3%A9", x)
      x <- gsub("É", "%C3%89", x)
      x <- gsub("è", "%C3%A8", x)
      x <- gsub("È", "%C3%88", x)
      x <- gsub("ê", "%C3%AA", x)
      x <- gsub("Ê", "%C3%8A", x)
      x <- gsub("ë", "%C3%AB", x)
      x <- gsub("Ë", "%C3%8B", x)
 return(x)
 }
```

I'm sure there are more

I'm not sure, but it might be of some use to include some similar function in the package or mention it in the documentation.

**Comment by Ironholds** [comment]
There are absolutely more, yep; check out the Wikipedia article on percent encoding. I actually wrote the sorta-gold-standard of URL encoders for R!

Absent that gold standard (which is a big dependency to bring into this project - it relies on Rcpp and other niceness) I'll just URL-encode the parameters using curl's encoder. Good idea.

**Comment by Ironholds** [comment]
Okay, try the dev version and see if it does what you want.

**Comment by ThomasWilli** [comment]
Works perfectly, thanks!
